default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: development_pg

test:
  <<: *default
  database: test_pg

production:
  <<: *default
  database: production_pg
